version: '3.8'
services:
  mcp-server:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/mcp
      - N8N_URL=http://n8n:5678
      - N8N_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNzNhZTBhMS0yOWIwLTQ4N2YtYWUxOS0wMjA3ZTYzMGU5YzIiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzQ5MTUxMDI4fQ.-Q_KPBGCbIoUELiEBvl0RgVo_PgugCHvEPfcQMH7aGE
      - NODE_ENV=production
      - API_KEY=changeme
      # Add SaaS/monetization env vars here (e.g., STRIPE_KEY, PLAN_ID, etc.)
    volumes:
      - ./memory:/app/memory
      - ./docs:/app/docs
    depends_on:
      - postgres
      - n8n

  postgres:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mcp
    ports:
      - "5433:5432"

  n8n:
    image: n8nio/n8n
    ports:
      - "5679:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_URL=http://n8n:5678

volumes:
  pgdata:
